server:
  port: 8888

spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://127.0.0.1:3306/stock?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false

  data:
    redis:
      database: 0
      host: 127.0.0.1
      port: 6379
      password:
      timeout: 2000
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
  servlet:
    multipart:
      # 上传文件的大小限制
      max-file-size: 2000MB
      max-request-size: 2000MB


mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true

logging:
  config: classpath:conf/logback-dev.xml

# 文件上传路径配置
# 注意：所有目录路径最后不用斜杠
upload-config:
  local-parent-dir: E:\Users\chenliang\upload   #/Users/chenliang/upload
  local-image-dir: E:\Users\chenliang\upload\image #/Users/chenliang/upload/image
  local-rel-image-dir:   E:\Users\upload\image   # /upload/image
  local-video-dir: E:\Users\chenliang\upload\video  #/Users/chenliang/upload/video
  # 本地图片加密之后的路径
  local-enc-image-dir: E:\Users\chenliang\upload\enc\image   # /Users/chenliang/upload/enc/image
  # 开发时上传到云服务器的目录
  cloud-parent-dir: /test/
  cloud-image-dir: /test/image
  cloud-video-dir: /test/video

# 视频文件需要切片成m3u8
video-process-config:
  # ffmpeg可执行文件所在目录
  ffmpeg-dir: D:\ffmpeg\bin  #/Users/chenliang/tools
  # 视频切片成m3u8所在目录，这里的文件需要上传到云服务器
  local-m3u8-dir: E:\mp4   #/Users/chenliang/m3u8
